[project]
name = "jarvis-shared"
version = "0.1.0"
description = "Shared utilities and types for Jarvis"
dependencies = [
    "pydantic>=2.8.0",
    "pydantic-settings>=2.0.0",
    "typing-extensions>=4.12.0",
    "rich>=13.7.0",
    "toml>=0.10.2",
]
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
