[project]
name = "jarvis-mcp-orchestrator"
version = "0.1.0"
description = "MCP Orchestrator for Jarvis - consolidates all MCP tools"
authors = [
    {name = "Armand Blin", email = "armand.blin@gmail.com"},
]
dependencies = [
    "jarvis-shared",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.8.0",
    "aiohttp>=3.12.15",
    "google-auth>=2.29.0",
    "google-auth-oauthlib>=1.2.0",
    "google-auth-httplib2>=0.2.0",
    "google-api-python-client>=2.140.0",
    "jarvis-gmail",
    "jarvis-calendar", 
    "jarvis-notification",
    "jarvis-hue",
]
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["jarvis_mcp_orchestrator"]
