[project]
name = "jarvis-whisper-service"
version = "0.1.0"
description = "Dedicated Whisper service for STT/TTS functionality"
authors = [
    {name = "Armand Blin", email = "armand.blin@gmail.com"},
]
dependencies = [
    "jarvis-shared",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.8.0",
    "aiofiles>=23.2.0",
    "numpy>=1.24.0",
    "soundfile>=0.12.1",
    "librosa>=0.10.1",
    "edge-tts>=6.1.0",
    "pydub>=0.25.1",
]
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["jarvis_whisper_service"]
