[project]
name = "jarvis-llm"
version = "0.1.0"
description = "Local LLM integration service for Jarvis"
dependencies = [
    "jarvis-shared",
    "ollama>=0.3.0",
]
requires-python = ">=3.11"

[tool.uv.sources]
jarvis-shared = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
