[project]
name = "jarvis-hue"
version = "0.1.0"
description = "Philips Hue integration tool for Jarvis"
dependencies = [
    "jarvis-shared",
    "aiohttp>=3.9.0",
]
requires-python = ">=3.11"

[tool.uv.sources]
jarvis-shared = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
