[project]
name = "jarvis-main-orchestrator"
version = "0.1.0"
description = "Main Orchestrator for Jarvis - coordinates all services"
authors = [
    {name = "Armand Blin", email = "armand.blin@gmail.com"},
]
dependencies = [
    "jarvis-shared",
    "jarvis-mcp-orchestrator",
    "jarvis-whisper-service",
    "jarvis-llm",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.8.0",
    "aiohttp>=3.12.15",
    "typer>=0.12.0",
    "rich>=13.7.0",
]
requires-python = ">=3.11"

[project.scripts]
jarvis = "jarvis_main_orchestrator.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["jarvis_main_orchestrator"]
