# Default configuration for Jarvis AI Assistant

[general]
debug = false
log_level = "DEBUG"

[ollama]
host = "http://localhost:11434"
model = "llama3.2:3b"
temperature = 0.1
timeout = 120

[mcp]
host = "localhost"
port = 3000
timeout = 30

[google]
credentials_file = "~/.jarvis/google_credentials.json"
token_file = "~/.jarvis/google_token.json"
scopes = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/calendar.readonly",
    "https://www.googleapis.com/auth/calendar.events",
]

[logging]
level = "INFO"
dir = "./logs"
console = false
file = true
rich = true
max_size = 10485760  # 10MB
backup_count = 5
date_format = "%Y-%m-%d %H:%M:%S"

[whisper]
model_path = "models/ggml-base.en.bin"
whisper_cpp_path = "whisper.cpp/build/bin/whisper-cli"
language = "en"
temperature = 0.0
max_len = 448

[tts]
engine = "edge"
voice = "en-US-ChristopherNeural"
rate = 50
volume = 1

[hue]
bridge_ip = "192.168.1.10"
username = "HwsEzhoVGhxwqDPKyBEBe1eXzfuzE-G0fa3O6arJ"
auto_discover = true
timeout = 10
