[project]
name = "jarvis-core"
version = "0.1.0"
description = "Core Jarvis assistant logic"
dependencies = [
    "jarvis-shared",
    "ollama>=0.3.0",
    "mcp>=1.0.0",
    "rich>=13.7.0",
    "asyncio>=3.4.3",
]
requires-python = ">=3.11"

[tool.uv.sources]
jarvis-shared = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
