[project]
name = "jarvis-notification"
version = "0.1.0"
description = "Notification and reminder tool for Jarvis"
dependencies = [
    "jarvis-shared",
    "plyer>=2.1.0",  # Cross-platform notifications
    "schedule>=1.2.0",  # Task scheduling
]
requires-python = ">=3.11"

[tool.uv.sources]
jarvis-shared = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
