[project]
name = "jarvis-mcp"
version = "0.1.0"
description = "MCP server for Jarvis tool orchestration"
dependencies = [
    "jarvis-shared",
    "mcp>=1.0.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
]
requires-python = ">=3.11"

[tool.uv.sources]
jarvis-shared = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
