name: Quick Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --dev

      - name: Quick lint check
        run: uv run ruff check . --output-format=github

      - name: Format check
        run: uv run black --check --diff .

      - name: Run fast unit tests only
        run: uv run pytest tests/unit/ -v --tb=short -x --disable-warnings
